config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "users#home"
  post "/new_user_post" => "posts#create"
  get "/login_form" => "users#login_form"
  post "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/home" => "users#home"
  get "/comments" => "users#posts"

  resources :users do
      resources :posts
      resources :addresses
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    validates :username, presence: true, uniqueness: true
    validates :password, confirmation: true
    validates :password_confirmation, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def new_user_post
      puts "\n****** new_user_post ******"
  end

  def home
      puts "\n****** home ******"
      @users = User.all
      if session[:user_id]
          @user =  User.find(session[:user_id])
          @address = Address.new
          @post = Post.new
      else
          puts "\n****** @user.inspect, #{@user.inspect} ******"
          redirect_to "/login_form"
      end
  end

  def edit
	@post = Post.find(params[:id])		# get the post for which the comment is created
	@comment = Comment.new					# generate a new comment object to hold submitted data
  end

  def login_form
      puts "\n****** login_form ******"
  end

    def login
          puts "\n******* login *******"
          @user = User.where(username: params[:username]).first
          if @user
              if @user.password == params[:password]
                    session[:user_id] = @user.id
                    #puts "asdf  mfhds #{@current_user.inspect}"
              @current_user = User.find_by_id(@user.id)
              puts "\n******* login successful *******"
              puts "\ncurrent_user: #{@current_user.inspect}"
                  flash[:notice] = "You've been signed in successfully."
                  redirect_to '/home'
              else
                  flash[:notice] = "Please check your password and try again."
                  redirect_to "/login_form"
              end
          else
              flash[:notice] = "Please check your username and try again."
              redirect_to "/login_form"
          end
      end

    def logout
        session.delete(:user_id)
        flash[:notice] = "You've been signed out successfully."
        redirect_to root_url
    end


  # GET /users
  # GET /users.json
  def index
    puts "\n****** index ******"
    @users = User.all
    puts "******* @users, #{@users.inspect}"
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
    puts "***** user_params *****"
    params.require(:user).permit(:firstname, :lastname, :email, :username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @user do |form| %>
      <div>
          <div class="data">
              <%= label :username, "username", id: "username", class: "data-label" %>
              <%= form.text_field :username, id: "username", class: "data-value" %>
          </div>
          <div class="data">
              <%= label :password, "password", id: "password", class: "data-label" %>
              <%= form.text_field :password, id: "password", class: "data-value" %>
          </div>
          <div class="data">
              <%= label :password_confirmation, "password_confirmation", id: "password_confirmation", class: "data-label" %>
              <%= form.text_field :password_confirmation, id: "password_confirmation", class: "data-value" %>
          </div>
          <div class="data">
              <%= form.submit %>
          </div>
      </div>
  <% end %>
<% end %>

<% if @user.errors.full_messages.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<h1>Welcome!</h1>

<h2>Please click on the Login_form link, so you can Login and write an awesome blog post!</h2>
<h3>(FYI, you can try to post without logging in, but we won't like that, and won't let you)</h3>

<%= link_to 'Address', new_user_address_path(@user) %>

<div>New Post</div>

<%= form_with url: "/new_user_post", method: "post" do |form| %>
    <div><%= label :title, "title" %><%= form.text_field :title %></div>
    <div><%= label :content, "content" %><%= form.text_field :content %></div>
    <div><%= form.submit "Submit" %></div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%  puts "******* @users, #{@users.inspect}"  %>
    <% @users.each do |user| %>
        <% puts "******* user, #{user.inspect}" %>
          <tr>

          <td><%= link_to "#{user.firstname}" + " " + "#{user.lastname}" + " " + "#{user.password}", user_path(user) %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to "posts", user_posts_path(user) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_with url: "/login", method: "post" do |form| %>
    <div><%= label :username, "username" %><%= form.text_field :username %></div>
    <div><%= label :password, "password" %><%= form.text_field :password %></div>
    <div><%= form.submit "Submit" %></div>
<% end %>

app/views/users/login_form.html.erb
<h1>Login</h1>

<%= form_with url: "/login", method: "post" do |form| %>
    <div><%= label :username, "username" %><%= form.text_field :username %></div>
    <div><%= label :password, "password" %><%= form.text_field :password %></div>
    <div><%= form.submit "Submit" %></div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% @posts.each do |post| %>
    <div>
        <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
        <h3><%= post.content %></h3>
    </div>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>