config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "users#home"
  post "/new_user_post" => "posts#create"
  get "/login_form" => "users#login_form"
  post "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/home" => "users#home"
  get "/comments" => "users#posts"

  resources :users do
      resources :posts
      resources :addresses
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    puts "\n******* new *******"
    @address = Address.new
    @user = User.find(session[:user_id])
    puts "\n****@user.inspect, #{@user.inspect}****"
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
      puts "\n******* create *******"
    @address = Address.new(address_params)
    @user = User.find(session[:user_id])

    respond_to do |format|
      if @address.save
        format.html { redirect_to "/users", notice: 'Address was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:user_id, :street, :city, :state, :zip)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for([@user, @address]) do |form| %>
      <% if address.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

          <ul>
          <% address.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <div class="field">
       <%= form.label :street %>
       <%= form.text_area :street, id: :street_id %>
    </div>

    <div class="field">
        <%= form.label :city %>
        <%= form.text_area :city, id: :city_id %>
    </div>

    <div class="field">
       <%= form.label :state %>
       <%= form.text_area :state, id: :state_id %>
    </div>

    <div class="field">
       <%= form.label :zip %>
       <%= form.text_area :zip, id: :zip_id %>
    </div>

    <input type="hidden" name="address[user_id]" value="<%= @user.id %>">

    <div class="actions">
      <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>