config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "users#home"
  post "/new_user_post" => "posts#create"
  get "/login_form" => "users#login_form"
  post "/login" => "users#login"
  get "/logout" => "users#logout"
  get "/home" => "users#home"
  get "/comments" => "users#posts"

  resources :users do
      resources :posts
      resources :addresses
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :post_tags
  has_many :tags, through: :post_tags
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
      puts "\n****index*****"
      puts "****params.inspect, #{params.inspect}****"
      @user = User.find(params[:user_id])
      @posts = @user.posts
      puts "****@posts.inspect, #{@posts.inspect}****"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @comment = @post.comments.build(user: @user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end


  # POST /posts
  # POST /posts.json
  def create
    @user = User.find_by(id: session[:user_id])

    @post = Post.new(
        title: params[:title],
        content: params[:content],
        user_id: @user.id
    )

    p @post

    respond_to do |format|
      if @post.save
          p "saved"

        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
          p "not saved"
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @user.posts.find(params[:id])
    end

    def set_user
        @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <%= form_with model: @post do |form| %>
      <div>
          <div class="data">
              <%= label :title, "title", id: "title", class: "data-label" %>
              <%= form.text_field :title, id: "title", class: "data-value" %>
          </div>
          <div class="data">
              <%= label :content, "content", id: "content", class: "data-label" %>
              <%= form.text_field :content, id: "content", class: "data-value" %>
          </div>
          <div class="data">
              <%= form.submit %>
          </div>
      </div>
  <% end %> -->

 <%= form_with(model: post, local: true) do |form| %>
 <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', user_posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<h2><%= @user.username %></h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @post.title %></h3>
<p><%= @post.content %></p>

<h4>Comments</h4>

<%= form_for @comment do |f| %>
    <%= f.text_field :body %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :post_id %>

    <%= f.submit %>
<% end %>

<% @post.comments.each do |comment| %>
    <p><b><%= comment.user.username %></b> <%= comment.body %></p>
<% end %>


<%= link_to 'Edit', edit_user_post_path([@current_user, @post]) %> |
<%= link_to 'Back', user_posts_path %>